function getRandomArbitrary(min: number, max: number) {
  return Math.random() * (max - min) + min;
}

export const notes = [
  {
    subject: "PORTUGUÊS",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
  {
    subject: "FÍSICA",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
  {
    subject: "QUÍMICA",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
  {
    subject: "MATEMÁTICA",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
  {
    subject: "HISTÓRIA",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
  {
    subject: "GEOGRAFIA",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
  {
    subject: "EDUCAÇÃO FÍSICA",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
  {
    subject: "INGLÊS",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
  {
    subject: "ESPANHOL",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
  {
    subject: "FILOSOFIA",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
  {
    subject: "SOCIOLOGIA",
    b1: Number(getRandomArbitrary(4, 10).toFixed()),
    b2: Number(getRandomArbitrary(4, 10).toFixed()),
    b3: Number(getRandomArbitrary(4, 10).toFixed()),
    b4: Number(getRandomArbitrary(4, 10).toFixed()),
    rec: Number(getRandomArbitrary(4, 10).toFixed()),
  },
];
